version: "3.9"

services:
  db:
    image: postgres:15
    container_name: data-base
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-claroapp}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: backend-server-gunicorn
    restart: always
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
      DJANGO_DEBUG: "True"
      POSTGRES_DB: ${POSTGRES_DB:-claroapp}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    volumes:
      - .:/code               # código en caliente para desarrollo
      - static_volume:/code/static_root
    expose:
      - "8000"                # sólo visible para nginx, no al host

  nginx:
    image: nginx:1.27-alpine
    container_name: frontend-server-nginx
    restart: always
    depends_on:
      - web
    ports:
      - "8080:80"             # entras por http://localhost:8080
    volumes:
    #  - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/code/static_root

volumes:
  postgres_data:
  static_volume:
